name: AutoTreeChopPlus
version: '${version}'
main: org.atcplus.autotreechopplus.AutoTreeChopPlus
api-version: 1.17
authors:
  - Maoyue
  - ATCPlus Team
description: Modernized fork of AutoTreeChop with quality-of-life improvements.
softdepend: [ PlaceholderAPI, Residence, Lands, WorldGuard ]
folia-supported: true

commands:
  autotreechop:
    description: Toggle AutoTreeChopPlus.
    usage: /autotreechop
    aliases: [ autotreechopplus, atcplus ]
    permission: atcplus.use
  atc:
    description: Toggle AutoTreeChopPlus.
    usage: /atc
    permission: atcplus.use

permissions:
  atcplus.use:
    description: Allows players to use AutoTreeChopPlus commands.
    default: true
  atcplus.replant:
    description: Allows auto-replanting of saplings.
    default: true
  atcplus.leaves:
    description: Allows automatic leaf removal.
    default: true
  atcplus.vip:
    description: VIP permission bypasses usage limits.
    default: op
  atcplus.other:
    description: Allows players to toggle AutoTreeChopPlus for others.
    default: op
  atcplus.op:
    description: Legacy operator permission for global toggles.
    default: op
  atcplus.reload:
    description: Allows reloading AutoTreeChopPlus configuration.
    default: op
